_root:
  paginator:
    enable: false
  rss:
    enable: false

weeks:
  paginator:
    enable: false
  layout: week
  sort: ["title", "desc"]

assignments:
  paginator:
    enable: false
  layout: assignment
  sort: ["due", "desc"]

base_path: '/iafl-2014fall'
production_url: 'http://marty-mcguire.com'
